[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:84 Destroying second model
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.1.8    unsupported  02:22:35Z

App                  Version  Status  Scale  Charm                Channel        Rev  Exposed  Message
postgresql           14.11    active      3  postgresql                            0  no       Primary
postgresql-test-app           active      1  postgresql-test-app  latest/stable  144  no       received database credentials of the first database

Unit                    Workload     Agent      Machine  Public address  Ports     Message
postgresql-test-app/0*  active       idle       3        10.46.7.101               received database credentials of the first database
postgresql/0            active       executing  0        10.46.7.182     5432/tcp  
postgresql/1            error        idle       1        10.46.7.47      5432/tcp  hook failed: "replication-offer-relation-broken"
postgresql/2*           maintenance  executing  2        10.46.7.2       5432/tcp  reconfiguring cluster

Machine  State    Address      Inst id        Base          AZ  Message
0        started  10.46.7.182  juju-19c8e2-0  ubuntu@22.04      Running
1        started  10.46.7.47   juju-19c8e2-1  ubuntu@22.04      Running
2        started  10.46.7.2    juju-19c8e2-2  ubuntu@22.04      Running
3        started  10.46.7.101  juju-19c8e2-3  ubuntu@22.04      Running

Offer              Application  Charm       Rev  Connected  Endpoint           Interface         Role
replication        postgresql   postgresql  0    0/0        replication        postgresql_async  requirer
replication-offer  postgresql   postgresql  0    1/1        replication-offer  postgresql_async  provider

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-2: 01:34:45 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:34:45 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:34:45 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
unit-postgresql-2: 01:34:46 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:34:55 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-0: 01:34:55 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:34:56 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-0: 01:34:56 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:35:04 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-1: 01:35:04 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:35:04 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-1: 01:35:06 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:36:28 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:36:28 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-3: 01:36:28 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-test-app-0: 01:36:30 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-1: 02:11:17 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "10883686-d4bf-4e81-8b4d-88f04b19c8e2:r#5#remote-eaa4466dd51641c480f2cad5e99118b0": settings 10883686-d4bf-4e81-8b4d-88f04b19c8e2:r#5#remote-eaa4466dd51641c480f2cad5e99118b0 not found (not found)
unit-postgresql-2: 02:11:17 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "10883686-d4bf-4e81-8b4d-88f04b19c8e2:r#5#remote-eaa4466dd51641c480f2cad5e99118b0": settings 10883686-d4bf-4e81-8b4d-88f04b19c8e2:r#5#remote-eaa4466dd51641c480f2cad5e99118b0 not found (not found)
unit-postgresql-2: 02:11:54 ERROR unit.postgresql/2.juju-log Failed to delete user: cannot execute REASSIGN OWNED in a read-only transaction

unit-postgresql-2: 02:11:54 ERROR unit.postgresql/2.juju-log Failed to delete user relation-5
unit-postgresql-2: 02:12:00 ERROR unit.postgresql/2.juju-log Failed to delete user: cannot execute REASSIGN OWNED in a read-only transaction

unit-postgresql-2: 02:12:00 ERROR unit.postgresql/2.juju-log Failed to delete user relation-5
unit-postgresql-2: 02:12:09 ERROR unit.postgresql/2.juju-log Failed to delete user: cannot execute REASSIGN OWNED in a read-only transaction

unit-postgresql-2: 02:12:09 ERROR unit.postgresql/2.juju-log Failed to delete user relation-5
unit-postgresql-1: 02:22:27 ERROR unit.postgresql/1.juju-log replication-offer:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/./src/charm.py", line 1702, in <module>
    main(PostgresqlOperatorCharm)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/main.py", line 548, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/main.py", line 527, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/main.py", line 516, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 544, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-1/charm/src/relations/async_replication.py", line 484, in _on_async_relation_broken
    if "departing" in self.charm._peers.data[self.charm.unit]:
AttributeError: 'NoneType' object has no attribute 'data'
unit-postgresql-1: 02:22:27 ERROR juju.worker.uniter.operation hook "replication-offer-relation-broken" (via hook dispatching script: dispatch) failed: exit status 1
unit-postgresql-1: 02:22:33 ERROR unit.postgresql/1.juju-log replication-offer:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/./src/charm.py", line 1702, in <module>
    main(PostgresqlOperatorCharm)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/main.py", line 548, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/main.py", line 527, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/main.py", line 516, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 544, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-1/charm/src/relations/async_replication.py", line 484, in _on_async_relation_broken
    if "departing" in self.charm._peers.data[self.charm.unit]:
AttributeError: 'NoneType' object has no attribute 'data'
unit-postgresql-1: 02:22:33 ERROR juju.worker.uniter.operation hook "replication-offer-relation-broken" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...