[1m[31mERROR   [0m integration.helpers:helpers.py:929 
[1m[31mERROR   [0m integration.helpers:helpers.py:929 
[1m[31mERROR   [0m integration.helpers:helpers.py:929
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.4.5    unsupported  01:59:27Z

App         Version  Status  Scale  Charm       Channel  Rev  Exposed  Message
postgresql  14.12    active      3  postgresql             0  no       

Unit           Workload  Agent  Machine  Public address  Ports     Message
postgresql/0*  active    idle   0        10.42.189.230   5432/tcp  
postgresql/1   active    idle   1        10.42.189.171   5432/tcp  
postgresql/2   active    idle   2        10.42.189.223   5432/tcp  

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.42.189.230  juju-d8fcea-0  ubuntu@22.04      Running
1        started  10.42.189.171  juju-d8fcea-1  ubuntu@22.04      Running
2        started  10.42.189.223  juju-d8fcea-2  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-0: 01:47:09 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:47:09 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-0: 01:47:09 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:47:14 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:47:14 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-2: 01:47:15 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:47:17 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:47:17 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-1: 01:47:17 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-0: 01:59:18 ERROR unit.postgresql/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/model.py", line 3187, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-postgresql-0/secret-set', 'secret:cqrcdjjrtnv3k733ok50', 'backup-password#file=/tmp/tmpgrunsuat/backup-password', 'monitoring-password#file=/tmp/tmpgrunsuat/monitoring-password', 'operator-password#file=/tmp/tmpgrunsuat/operator-password', 'replication-password#file=/tmp/tmpgrunsuat/replication-password', 'rewind-password#file=/tmp/tmpgrunsuat/rewind-password')' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/./src/charm.py", line 1859, in <module>
    main(PostgresqlOperatorCharm)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 647, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-0/charm/./src/charm.py", line 1298, in _on_set_password
    self.set_secret(APP_SCOPE, f"{username}-password", password)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 647, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-0/charm/./src/charm.py", line 315, in set_secret
    self.peer_relation_data(scope).set_secret(peers.id, secret_key, value)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 519, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1860, in set_secret
    self.update_relation_data(relation_id, {full_field: value})
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 494, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1268, in update_relation_data
    return self._update_relation_data(relation, data)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 534, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2090, in _update_relation_data
    _, normal_fields = self._process_secret_fields(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1067, in _process_secret_fields
    if group_result := operation(relation, group, secret_fields, *args, **kwargs):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1391, in _add_or_update_relation_secrets
    return self._update_relation_secret(relation, group, secret_fields, data)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 506, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1376, in _update_relation_secret
    secret.set_content(full_content)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 667, in set_content
    self.meta.set_content(content)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/model.py", line 1438, in set_content
    self._backend.secret_set(typing.cast(str, self.id), content=content)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/model.py", line 3607, in secret_set
    self._run_for_secret('secret-set', *args)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/model.py", line 3563, in _run_for_secret
    return self._run(*args, return_output=return_output, use_json=use_json)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/model.py", line 3189, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR secret content in file "/tmp/tmpgrunsuat/replication-password" too large: 2000000 bytes


[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...